<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'voku\\' => array($vendorDir . '/voku/portable-ascii/src/voku'),
    'StraussIlluminateContracts\\Deps\\Symfony\\Polyfill\\Php83\\' => array($vendorDir . '/symfony/polyfill-php83'),
    'StraussIlluminateContracts\\Deps\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'StraussIlluminateContracts\\Deps\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'StraussIlluminateContracts\\Deps\\Symfony\\Contracts\\Translation\\' => array($vendorDir . '/symfony/translation-contracts'),
    'StraussIlluminateContracts\\Deps\\Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'StraussIlluminateContracts\\Deps\\Symfony\\Component\\Clock\\' => array($vendorDir . '/symfony/clock'),
    'StraussIlluminateContracts\\Deps\\Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'StraussIlluminateContracts\\Deps\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'StraussIlluminateContracts\\Deps\\Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'StraussIlluminateContracts\\Deps\\Illuminate\\Support\\' => array($vendorDir . '/illuminate/support', $vendorDir . '/illuminate/collections', $vendorDir . '/illuminate/macroable', $vendorDir . '/illuminate/conditionable'),
    'StraussIlluminateContracts\\Deps\\Doctrine\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib/Doctrine/Inflector'),
    'StraussIlluminateContracts\\Deps\\Carbon\\Doctrine\\' => array($vendorDir . '/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine'),
    'StraussIlluminateContracts\\Deps\\Carbon\\' => array($vendorDir . '/nesbot/carbon/src/Carbon'),
    'Illuminate\\Contracts\\' => array($vendorDir . '/illuminate/contracts'),
    'Dartui\\StraussIlluminateContracts\\' => array($baseDir . '/src'),
);
